openapi: 3.0.0
info:
  title: IMBAG API - van de LVBAG
  description: '"Dit is de BAG API van de landelijke voorziening BAG (LVBAG) voor
    het informatiemodel IMBAG 2.0 en conform de API strategie 1.1 specificatie in
    OAS3. Deze is vooral gericht op individuele bevragingen (op basis van de identificerende
    gegevens van een object).  <br/><br/> Meer informatie over BAG 2.0 is te vinden
    op: [Catalogus BAG 2.0](https://www.geobasisregistraties.nl/basisregistraties/adressen-en-gebouwen)
    <br/> Meer informatie over Nederlandse API strategie is te vinden op: [API-Strategie](https://docs.geostandaarden.nl/api/API-Strategie)
    - deze API volgt versie 1.1 van 20190213.  <br/> Meer informatie over OAS3 specificatie
    is te vinden op: [OAS](https://www.forumstandaardisatie.nl/standaard/openapi-specification)   <br/>
    Het standaard mediatype HAL (`application/hal+json`) wordt gebruikt. Dit is een
    mediatype voor het weergeven van resources en hun relaties via hyperlinks. <br/>
    <br/> Voor vragen, neem contact op met de BAG beheerder o.v.v. BAG API 2.0. We
    zijn aan het kijken naar een geschikt medium hiervoor, mede ook om de API iteratief
    te kunnen opstellen of doorontwikkelen samen met de community. Als de API iets
    (nog) niet kan, wat u wel graag wilt, neem dan contact op.  <br/> <br/> Een API-key
    kan verkregen worden door een e-mail te sturen naar: zie onderstaande contactgegevens
    <font color=''blue''>send e-mail</font>." '
  termsOfService: https://zakelijk.kadaster.nl/algemene-voorwaarden
  contact:
    name: Kadaster - Beheerder Landelijke Voorziening BAG
    url: https://zakelijk.kadaster.nl/bag
    email: bag@kadaster.nl
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
  version: 2.0.0
servers:
- url: https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2
  description: LVBAG - ACCEPTATIE
- url: https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2
  description: LVBAG - PRODUCTIE
security:
- apiKeyBAG: []
tags:
- name: Algemene informatie
  description: Het endpoint voor algemene informatie levert informatie op van de API.
paths:
  /info:
    get:
      tags:
      - Algemene informatie
      summary: Algemene info van de API
      operationId: getInfo
      responses:
        "200":
          description: Bevraging getInfo geslaagd
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/API-info'
        default:
          description: Onverwacht probleem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - apiKeyBAG: []
components:
  schemas:
    API-info:
      title: API-info
      type: object
      properties:
        api-name:
          type: string
          description: De naam van de API.
        api-version:
          type: string
          description: Versie van de API.
        api-description:
          type: string
          description: Omschrijving van de API.
        informationmodel:
          type: string
          description: Naam van het informatiemodel dat als basis is genomen voor
            deze API.
          example: IMBAGLV
        informationmodel-version:
          type: string
          description: Versie van het logische informatiemodel dat als basis is genomen
            voor deze API.
          example: v20190601
        informationmodel-location:
          type: string
          description: Locatie (URI) van het logische informatiemodel die als basis
            is genomen voor deze API.
          format: URI
    Error:
      title: Error
      required:
      - detail
      - instance
      - status
      - title
      - type
      type: object
      properties:
        status:
          type: integer
          description: De HTTP status code.
          example: 401
        title:
          type: string
          description: De titel behorende bij de HTTP status code.
          example: Niet correct geauthenticeerd
        type:
          type: string
          description: URI naar een pagina met meer informatie over deze foutmelding
            voor de ontwikkelaar.
          format: uri
          example: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#/10.4.2
            401 Unauthorized
        detail:
          type: string
          description: Een gedetailleerde beschrijving van de HTTP status code.
          example: Het verzoek vereist gebruikers authenticatie.
        instance:
          type: string
          description: URI van de aanroep die fout heeft veroorzaakt.
          format: uri
        code:
          minLength: 1
          type: string
          description: Systeem code die het type fout aangeeft.
        invalid-params:
          type: array
          items:
            $ref: '#/components/schemas/InvalidParams'
    InvalidParams:
      title: InvalidParams
      required:
      - code
      - name
      - reason
      type: object
      properties:
        type:
          type: string
          description: Een url naar een beschrijving van de fout in de parameter.
            De hier gerefereerde foutbeschrijving is specifieker dan type op het hoofdniveau
            van het bericht.
          format: uri
        name:
          type: string
          description: De naam van de parameter waar de fout in zit.
          example: geldigOp
        code:
          type: string
          description: Een vaste waarde afhankelijk van het soort fout.
          example: date
        reason:
          type: string
          description: Een vaste omschrijving afhankelijk van het soort fout.
          example: Waarde is geen geldige datum.
      description: 'Wanneer de fout is veroorzaakt door fouten in requestparameters
        (of request body), wordt invalid-params gevuld met details over elke foute
        parameter. Wanneer er fouten zitten op meerdere parameters, wordt er per validatiefout
        een invalid-params instantie opgenomen in het antwoord. Alle fouten worden
        dus teruggegeven. Een gedetailleerde beschrijving hoe de onderstaande attributen
        ingevuld moeten worden staat op: https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/foutafhandeling.feature'
  securitySchemes:
    apiKeyBAG:
      type: apiKey
      description: |
        De API-key die je hebt gekregen dient bij elke request via de  `X-Api-Key` request header meegestuurd te worden. Indien deze  niet juist wordt meegestuurd, of het een ongeldige key betreft,  zul je de foutmelding `403 Forbidden` terugkrijgen.
      name: X-Api-Key
      in: header
